### ISSUE TITLE
Can’t get StatsD running under nodyn

### ISSUE THREAD

**Issue by mrmanc** [nodyn/nodyn#75]
Hello. I am attempting to get [StatsD](https://github.com/etsy/statsd) running with nodyn and I am currently getting this rather confusing message. I’m aware that this is part of node, but not being familiar with node that’s about as far as I have got trying to get this working. Note: I’ve added ‘.js’ to the end of the require statements that pull in lib files to get to this point (see my git diff below).

Thanks in advance for help, and please forgive me if I’m trying to bend nodyn beyond it’s purpose.

```
$ ../nodyn/bin/nodyn stats.js exampleConfig.js.js
Successfully loaded native POSIX impl.
POSX: jnr.posix.LazyPOSIX@6d60a8d3
…
13 Aug 16:10:00 - reading config file: exampleConfig.js
buildStat.result: 0
buildStat.errno: 0
buildStat.result: 0
buildStat.errno: 2
Error: cannot load module nodyn/bindings/fs_event_wrap
  at <native function: Error> (org/dynjs/runtime/builtins/types/BuiltinError.java:0)
  at <native function: require> (org/dynjs/runtime/builtins/Require.java:0)
  at <eval> (<eval>:1)
```

I am running in OSX, running StatsD version 1d9d9bf32aa5c7fe4f48d61165bed805cc8f3480 and nodyn version 8c6aa1965bb0dac4c81ecb4bfe6591183bb2c5f5.

```
$ uname -a
Darwin MCR-AL17892.local 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64
```

```
$ git diff stats.js
diff --git a/stats.js b/stats.js
index ccfe676..2ad89cd 100644
--- a/stats.js
+++ b/stats.js
@@ -1,18 +1,18 @@
+//load('./lib/jvm-npm.js');
 /*jshint node:true, laxcomma:true */

 var dgram  = require('dgram')
   , util    = require('util')
   , net    = require('net')
-  , config = require('./lib/config')
-  , helpers = require('./lib/helpers')
+  , config = require('./lib/config.js')
+  , helpers = require('./lib/helpers.js')
   , fs     = require('fs')
   , events = require('events')
-  , logger = require('./lib/logger')
-  , set = require('./lib/set')
-  , pm = require('./lib/process_metrics')
-  , process_mgmt = require('./lib/process_mgmt')
-  , mgmt = require('./lib/mgmt_console');
-
+  , logger = require('./lib/logger.js')
+  , set = require('./lib/set.js')
+  , pm = require('./lib/process_metrics.js')
+  , process_mgmt = require('./lib/process_mgmt.js')
+  , mgmt = require('./lib/mgmt_console.js');

 // initialize data structures with defaults for statsd stats
 var keyCounter = {};
```

**Comment by chook** [comment]
@mrmanc were you ever able to run StatsD (js) on a JVM?

**Comment by mrmanc** [comment]
@chook No, but I’ve no reason to think it wouldn’t be possible at the moment.

**Comment by chook** [comment]
@mrmanc I get Error: cannot load module dgram ..

**Comment by mrmanc** [comment]
Well there was apparently a fix in 611a9fe. I tried to test with a current version of nodyn but struggling to build… I am getting 4 failing Jasmine tests.

```
  should be able to send sockets to a child ...
>> timed out after 15000 msec waiting for child process to be killed
 Failed
    timeout: timed out after 15000 msec waiting for child process to be killed
15 of 16 passed.
…
  should send the request when headers are implicitly sent ...
>> timed out after 15000 msec waiting for page to load
 Failed
    timeout: timed out after 15000 msec waiting for page to load
  should receive a "socket" event ...
>> timed out after 15000 msec waiting for page to load
 Failed
    timeout: timed out after 15000 msec waiting for page to load
  should allow later binding of a response-handler ...
>> timed out after 15000 msec waiting for page to load
 Failed
    timeout: timed out after 15000 msec waiting for page to load
1 of 4 passed.
…
FAILURE: 389 specs, 4 failures in 159.006s.
```

Running the previous version I built (on Aug 19th 2014), which I suspect was 611a9fe I get a message about it reading the example config I give it, then nothing, despite having debug and dumpMessages turned on, and sending to it using `echo "foo:1|c" | nc -u -w0 127.0.0.1 8125`. A `netstat -a | grep 8125` shows nothing listening on port 8125 so I don’t think it is working :( 

```
mark.crossfield@MCR-AL17892  15:58 ~/Documents/workspace/statsd
$ ../nodyn/bin/nodyn stats.js exampleConfig.js
7 Oct 15:58:32 - reading config file: exampleConfig.js
```

I tried checking out 611a9fe but it doesn’t build now due to failed dependencies. Sorry!

**Comment by lance** [comment]
Hey guys - I'm glad you are continuing to work with nodyn, but for most
purposes, development has pretty much stopped on this project. As you
progress, if you have contributions you'd like to make to fix bugs/issues,
please feel free to submit a PR.

Thanks
Lance

Lance Ball
http://lanceball.com

**Comment by chook** [comment]
Hi @lance thanks for replying. Have you written anywhere what "killed" the project?

**Comment by lance** [comment]
Chen

No official reasons have been written down publicly, but here is a little
back story. I was working on this as a research project for Red Hat. For
all of our research projects, we have evaluation points where we choose to
continue forward or kill the project. The criteria for these decisions
takes into account many things, including business interest from the sales
and marketing folks and community interest measured by things like pull
requests. The size and scope of this project, coupled with low scores for
these two metrics probably put the nail in the coffin. But there were other
contributing factors as well - including the fact that Avatar.js suffered a
similar fate with not much community outcry. It's always tough to kill your
babies, but that's the way it is in R&P. :/

Lance

Lance Ball
http://lanceball.com

**Comment by chook** [comment]
Thanks for sharing Lance, good luck! :+1:
