### ISSUE TITLE
Broken Links on JBoss.org

### ISSUE THREAD

**Issue by Dantheman720** [nodyn/nodyn#97]
The following broken links are currently listed against this project on www.jboss.org/projects.

http://nodyn.io/community/
http://nodyn.io/documentation/
http://nodyn.io/install/
http://nodyn.io/news/
http://nodyn.io/releases/

If you maintain a project.properties file that you have told the jboss.org team about, then you just need to fix it in there and the change will be reflected on the site. Otherwise, you need to update the data on this project's Magnolia page.

**Comment by Dantheman720** [comment]
@lance - Is it possible to change travis-ci.org/nodyn/nodyn to it's absolute path in the properties file?  Since we pull in many projects on JBoss.org, it is too difficult to adjust the rendering for individual projects.

**Comment by lance** [comment]
@Dantheman720 this has been fixed. I didn't realize that was the issue previously.
